export const REAL_SQUADS = {
  fla: [
    { nome: "Rossi", posicao: "GOL", overall: 82 },
    { nome: "Matheus Cunha", posicao: "GOL", overall: 75 },
    { nome: "Léo Pereira", posicao: "ZAG", overall: 83 },
    { nome: "Fabrício Bruno", posicao: "ZAG", overall: 81 },
    { nome: "Léo Ortiz", posicao: "ZAG", overall: 80 },
    { nome: "Ayrton Lucas", posicao: "LAT", overall: 81 },
    { nome: "Varela", posicao: "LAT", overall: 76 },
    { nome: "Pulgar", posicao: "VOL", overall: 79 },
    { nome: "Allan", posicao: "VOL", overall: 76 },
    { nome: "Arrascaeta", posicao: "MEI", overall: 86 },
    { nome: "De la Cruz", posicao: "MEI", overall: 84 },
    { nome: "Gerson", posicao: "MEI", overall: 83 },
    { nome: "Pedro", posicao: "ATA", overall: 86 },
    { nome: "Gabriel Barbosa", posicao: "ATA", overall: 80 },
    { nome: "Luiz Araújo", posicao: "ATA", overall: 79 }
  ],
  pal: [
    { nome: "Weverton", posicao: "GOL", overall: 83 },
    { nome: "Marcelo Lomba", posicao: "GOL", overall: 74 },
    { nome: "Gustavo Gómez", posicao: "ZAG", overall: 84 },
    { nome: "Murilo", posicao: "ZAG", overall: 82 },
    { nome: "Vitor Reis", posicao: "ZAG", overall: 77 },
    { nome: "Piquerez", posicao: "LAT", overall: 81 },
    { nome: "Marcos Rocha", posicao: "LAT", overall: 77 },
    { nome: "Aníbal Moreno", posicao: "VOL", overall: 80 },
    { nome: "Richard Ríos", posicao: "VOL", overall: 79 },
    { nome: "Raphael Veiga", posicao: "MEI", overall: 83 },
    { nome: "Maurício", posicao: "MEI", overall: 79 },
    { nome: "Zé Rafael", posicao: "MEI", overall: 79 },
    { nome: "Estêvão", posicao: "ATA", overall: 84 },
    { nome: "Flaco López", posicao: "ATA", overall: 81 },
    { nome: "Felipe Anderson", posicao: "ATA", overall: 82 }
  ],
  bot: [
    { nome: "John", posicao: "GOL", overall: 81 },
    { nome: "Gatito Fernández", posicao: "GOL", overall: 73 },
    { nome: "Bastos", posicao: "ZAG", overall: 81 },
    { nome: "Alexander Barboza", posicao: "ZAG", overall: 80 },
    { nome: "Adryelson", posicao: "ZAG", overall: 78 },
    { nome: "Alex Telles", posicao: "LAT", overall: 80 },
    { nome: "Vitinho", posicao: "LAT", overall: 78 },
    { nome: "Marlon Freitas", posicao: "VOL", overall: 81 },
    { nome: "Gregore", posicao: "VOL", overall: 79 },
    { nome: "Thiago Almada", posicao: "MEI", overall: 84 },
    { nome: "Eduardo", posicao: "MEI", overall: 77 },
    { nome: "Tchê Tchê", posicao: "MEI", overall: 76 },
    { nome: "Luiz Henrique", posicao: "ATA", overall: 84 },
    { nome: "Igor Jesus", posicao: "ATA", overall: 82 },
    { nome: "Savarino", posicao: "ATA", overall: 81 }
  ],
  spa: [
    { nome: "Rafael", posicao: "GOL", overall: 80 },
    { nome: "Jandrei", posicao: "GOL", overall: 72 },
    { nome: "Arboleda", posicao: "ZAG", overall: 81 },
    { nome: "Alan Franco", posicao: "ZAG", overall: 79 },
    { nome: "Ferraresi", posicao: "ZAG", overall: 76 },
    { nome: "Welington", posicao: "LAT", overall: 77 },
    { nome: "Igor Vinícius", posicao: "LAT", overall: 76 },
    { nome: "Alisson", posicao: "VOL", overall: 78 },
    { nome: "Luiz Gustavo", posicao: "VOL", overall: 77 },
    { nome: "Lucas Moura", posicao: "MEI", overall: 82 },
    { nome: "Luciano", posicao: "MEI", overall: 79 },
    { nome: "Rodrigo Nestor", posicao: "MEI", overall: 77 },
    { nome: "Calleri", posicao: "ATA", overall: 81 },
    { nome: "Ferreira", posicao: "ATA", overall: 78 },
    { nome: "Wellington Rato", posicao: "ATA", overall: 76 }
  ],
  cor: [
    { nome: "Hugo Souza", posicao: "GOL", overall: 80 },
    { nome: "Matheus Donelli", posicao: "GOL", overall: 71 },
    { nome: "André Ramalho", posicao: "ZAG", overall: 80 },
    { nome: "Gustavo Henrique", posicao: "ZAG", overall: 76 },
    { nome: "Cacá", posicao: "ZAG", overall: 76 },
    { nome: "Matheus Bidu", posicao: "LAT", overall: 75 },
    { nome: "Fagner", posicao: "LAT", overall: 75 },
    { nome: "José Martínez", posicao: "VOL", overall: 77 },
    { nome: "Breno Bidon", posicao: "VOL", overall: 75 },
    { nome: "Rodrigo Garro", posicao: "MEI", overall: 82 },
    { nome: "Igor Coronado", posicao: "MEI", overall: 78 },
    { nome: "Alex Santana", posicao: "MEI", overall: 75 },
    { nome: "Memphis Depay", posicao: "ATA", overall: 83 },
    { nome: "Yuri Alberto", posicao: "ATA", overall: 80 },
    { nome: "Ángel Romero", posicao: "ATA", overall: 77 }
  ],
  flu: [
    { nome: "Fábio", posicao: "GOL", overall: 79 },
    { nome: "Felipe Alves", posicao: "GOL", overall: 70 },
    { nome: "Thiago Silva", posicao: "ZAG", overall: 82 },
    { nome: "Thiago Santos", posicao: "ZAG", overall: 75 },
    { nome: "Ignácio", posicao: "ZAG", overall: 75 },
    { nome: "Marcelo", posicao: "LAT", overall: 79 },
    { nome: "Samuel Xavier", posicao: "LAT", overall: 75 },
    { nome: "Facundo Bernal", posicao: "VOL", overall: 77 },
    { nome: "Martinelli", posicao: "VOL", overall: 76 },
    { nome: "Ganso", posicao: "MEI", overall: 80 },
    { nome: "Lima", posicao: "MEI", overall: 75 },
    { nome: "Renato Augusto", posicao: "MEI", overall: 74 },
    { nome: "Jhon Arias", posicao: "ATA", overall: 83 },
    { nome: "Germán Cano", posicao: "ATA", overall: 79 },
    { nome: "Kauã Elias", posicao: "ATA", overall: 77 }
  ],
  vas: [
    { nome: "Léo Jardim", posicao: "GOL", overall: 81 },
    { nome: "Keiller", posicao: "GOL", overall: 70 },
    { nome: "João Victor", posicao: "ZAG", overall: 78 },
    { nome: "Maicon", posicao: "ZAG", overall: 74 },
    { nome: "Léo", posicao: "ZAG", overall: 73 },
    { nome: "Lucas Piton", posicao: "LAT", overall: 78 },
    { nome: "Paulo Henrique", posicao: "LAT", overall: 74 },
    { nome: "Hugo Moura", posicao: "VOL", overall: 76 },
    { nome: "Mateus Carvalho", posicao: "VOL", overall: 75 },
    { nome: "Philippe Coutinho", posicao: "MEI", overall: 79 },
    { nome: "Payet", posicao: "MEI", overall: 78 },
    { nome: "Sforza", posicao: "MEI", overall: 74 },
    { nome: "Vegetti", posicao: "ATA", overall: 81 },
    { nome: "David", posicao: "ATA", overall: 74 },
    { nome: "Rayan", posicao: "ATA", overall: 73 }
  ],
  cru: [
    { nome: "Cássio", posicao: "GOL", overall: 80 },
    { nome: "Anderson", posicao: "GOL", overall: 72 },
    { nome: "João Marcelo", posicao: "ZAG", overall: 78 },
    { nome: "Zé Ivaldo", posicao: "ZAG", overall: 77 },
    { nome: "Villalba", posicao: "ZAG", overall: 76 },
    { nome: "Marlon", posicao: "LAT", overall: 78 },
    { nome: "William", posicao: "LAT", overall: 80 },
    { nome: "Lucas Romero", posicao: "VOL", overall: 77 },
    { nome: "Walace", posicao: "VOL", overall: 77 },
    { nome: "Matheus Pereira", posicao: "MEI", overall: 83 },
    { nome: "Alvaro Barreal", posicao: "MEI", overall: 77 },
    { nome: "Lucas Silva", posicao: "MEI", overall: 75 },
    { nome: "Kaio Jorge", posicao: "ATA", overall: 78 },
    { nome: "Gabriel Veron", posicao: "ATA", overall: 77 },
    { nome: "Lautaro Díaz", posicao: "ATA", overall: 76 }
  ],
  gre: [
    { nome: "Marchesín", posicao: "GOL", overall: 78 },
    { nome: "Rafael Cabral", posicao: "GOL", overall: 72 },
    { nome: "Jemerson", posicao: "ZAG", overall: 77 },
    { nome: "Rodrigo Ely", posicao: "ZAG", overall: 76 },
    { nome: "Kannemann", posicao: "ZAG", overall: 77 },
    { nome: "Reinaldo", posicao: "LAT", overall: 77 },
    { nome: "João Pedro", posicao: "LAT", overall: 76 },
    { nome: "Villasanti", posicao: "VOL", overall: 80 },
    { nome: "Dodi", posicao: "VOL", overall: 75 },
    { nome: "Cristaldo", posicao: "MEI", overall: 80 },
    { nome: "Monsalve", posicao: "MEI", overall: 76 },
    { nome: "Pepê", posicao: "MEI", overall: 75 },
    { nome: "Braithwaite", posicao: "ATA", overall: 80 },
    { nome: "Soteldo", posicao: "ATA", overall: 80 },
    { nome: "Diego Costa", posicao: "ATA", overall: 78 }
  ],
  int: [
    { nome: "Rochet", posicao: "GOL", overall: 81 },
    { nome: "Anthoni", posicao: "GOL", overall: 71 },
    { nome: "Vitão", posicao: "ZAG", overall: 79 },
    { nome: "Gabriel Mercado", posicao: "ZAG", overall: 76 },
    { nome: "Rogel", posicao: "ZAG", overall: 75 },
    { nome: "Bernabei", posicao: "LAT", overall: 78 },
    { nome: "Bruno Gomes", posicao: "LAT", overall: 76 },
    { nome: "Thiago Maia", posicao: "VOL", overall: 78 },
    { nome: "Fernando", posicao: "VOL", overall: 78 },
    { nome: "Alan Patrick", posicao: "MEI", overall: 82 },
    { nome: "Bruno Henrique", posicao: "MEI", overall: 76 },
    { nome: "Hyoran", posicao: "MEI", overall: 74 },
    { nome: "Borré", posicao: "ATA", overall: 81 },
    { nome: "Enner Valencia", posicao: "ATA", overall: 79 },
    { nome: "Wesley", posicao: "ATA", overall: 78 }
  ],
  cam: [
    { nome: "Everson", posicao: "GOL", overall: 80 },
    { nome: "Matheus Mendes", posicao: "GOL", overall: 71 },
    { nome: "Junior Alonso", posicao: "ZAG", overall: 80 },
    { nome: "Lyanco", posicao: "ZAG", overall: 77 },
    { nome: "Battaglia", posicao: "ZAG", overall: 79 },
    { nome: "Guilherme Arana", posicao: "LAT", overall: 82 },
    { nome: "Saravia", posicao: "LAT", overall: 76 },
    { nome: "Otávio", posicao: "VOL", overall: 78 },
    { nome: "Fausto Vera", posicao: "VOL", overall: 77 },
    { nome: "Gustavo Scarpa", posicao: "MEI", overall: 81 },
    { nome: "Bernard", posicao: "MEI", overall: 76 },
    { nome: "Igor Gomes", posicao: "MEI", overall: 74 },
    { nome: "Hulk", posicao: "ATA", overall: 84 },
    { nome: "Paulinho", posicao: "ATA", overall: 82 },
    { nome: "Deyverson", posicao: "ATA", overall: 78 }
  ],
  bah: [
    { nome: "Marcos Felipe", posicao: "GOL", overall: 77 },
    { nome: "Adriel", posicao: "GOL", overall: 70 },
    { nome: "Kanu", posicao: "ZAG", overall: 76 },
    { nome: "Gabriel Xavier", posicao: "ZAG", overall: 77 },
    { nome: "Victor Cuesta", posicao: "ZAG", overall: 74 },
    { nome: "Luciano Juba", posicao: "LAT", overall: 76 },
    { nome: "Santiago Arias", posicao: "LAT", overall: 76 },
    { nome: "Caio Alexandre", posicao: "VOL", overall: 79 },
    { nome: "Jean Lucas", posicao: "VOL", overall: 78 },
    { nome: "Everton Ribeiro", posicao: "MEI", overall: 80 },
    { nome: "Cauly", posicao: "MEI", overall: 80 },
    { nome: "Carlos De Pena", posicao: "MEI", overall: 74 },
    { nome: "Everaldo", posicao: "ATA", overall: 77 },
    { nome: "Thaciano", posicao: "ATA", overall: 78 },
    { nome: "Lucho Rodríguez", posicao: "ATA", overall: 76 }
  ],
  for: [
    { nome: "João Ricardo", posicao: "GOL", overall: 78 },
    { nome: "Kozlinski", posicao: "GOL", overall: 68 },
    { nome: "Kuscevic", posicao: "ZAG", overall: 76 },
    { nome: "Brítez", posicao: "ZAG", overall: 76 },
    { nome: "Cardona", posicao: "ZAG", overall: 74 },
    { nome: "Felipe Jonatan", posicao: "LAT", overall: 75 },
    { nome: "Tinga", posicao: "LAT", overall: 76 },
    { nome: "Lucas Sasha", posicao: "VOL", overall: 75 },
    { nome: "Hércules", posicao: "VOL", overall: 77 },
    { nome: "Pochettino", posicao: "MEI", overall: 79 },
    { nome: "Calebe", posicao: "MEI", overall: 75 },
    { nome: "Kervin Andrade", posicao: "MEI", overall: 73 },
    { nome: "Lucero", posicao: "ATA", overall: 80 },
    { nome: "Yago Pikachu", posicao: "ATA", overall: 77 },
    { nome: "Breno Lopes", posicao: "ATA", overall: 76 }
  ],
  cea: [
    { nome: "Bruno Ferreira", posicao: "GOL", overall: 73 },
    { nome: "Richard", posicao: "GOL", overall: 69 },
    { nome: "David Ricardo", posicao: "ZAG", overall: 73 },
    { nome: "João Pedro", posicao: "ZAG", overall: 70 },
    { nome: "Ramon Menezes", posicao: "ZAG", overall: 70 },
    { nome: "Matheus Bahia", posicao: "LAT", overall: 72 },
    { nome: "Rafael Ramos", posicao: "LAT", overall: 70 },
    { nome: "Richardson", posicao: "VOL", overall: 71 },
    { nome: "De Lucca", posicao: "VOL", overall: 70 },
    { nome: "Mugni", posicao: "MEI", overall: 72 },
    { nome: "Recalde", posicao: "MEI", overall: 72 },
    { nome: "Lourenço", posicao: "MEI", overall: 71 },
    { nome: "Erick Pulga", posicao: "ATA", overall: 75 },
    { nome: "Aylon", posicao: "ATA", overall: 72 },
    { nome: "Saulo Mineiro", posicao: "ATA", overall: 73 }
  ],
  bra: [
    { nome: "Cleiton", posicao: "GOL", overall: 77 },
    { nome: "Lucão", posicao: "GOL", overall: 68 },
    { nome: "Douglas Mendes", posicao: "ZAG", overall: 75 },
    { nome: "Pedro Henrique", posicao: "ZAG", overall: 75 },
    { nome: "Lucas Cunha", posicao: "ZAG", overall: 74 },
    { nome: "Luan Cândido", posicao: "LAT", overall: 76 },
    { nome: "Nathan Mendes", posicao: "LAT", overall: 75 },
    { nome: "Jadsom", posicao: "VOL", overall: 75 },
    { nome: "Raul", posicao: "VOL", overall: 74 },
    { nome: "Lucas Evangelista", posicao: "MEI", overall: 77 },
    { nome: "Lincoln", posicao: "MEI", overall: 75 },
    { nome: "Gustavinho", posicao: "MEI", overall: 72 },
    { nome: "Eduardo Sasha", posicao: "ATA", overall: 77 },
    { nome: "Helinho", posicao: "ATA", overall: 79 },
    { nome: "Vitinho", posicao: "ATA", overall: 75 }
  ],
  cap: [
    { nome: "Mycael", posicao: "GOL", overall: 76 },
    { nome: "Léo Linck", posicao: "GOL", overall: 72 },
    { nome: "Thiago Heleno", posicao: "ZAG", overall: 76 },
    { nome: "Gamarra", posicao: "ZAG", overall: 75 },
    { nome: "Kaique Rocha", posicao: "ZAG", overall: 74 },
    { nome: "Esquivel", posicao: "LAT", overall: 77 },
    { nome: "Madson", posicao: "LAT", overall: 74 },
    { nome: "Gabriel", posicao: "VOL", overall: 75 },
    { nome: "Felipinho", posicao: "VOL", overall: 74 },
    { nome: "Fernandinho", posicao: "MEI", overall: 78 },
    { nome: "Zapelli", posicao: "MEI", overall: 76 },
    { nome: "Christian", posicao: "MEI", overall: 75 },
    { nome: "Mastriani", posicao: "ATA", overall: 77 },
    { nome: "Canobbio", posicao: "ATA", overall: 77 },
    { nome: "Julimar", posicao: "ATA", overall: 75 }
  ],
  san: [
    { nome: "Gabriel Brazão", posicao: "GOL", overall: 75 },
    { nome: "Diógenes", posicao: "GOL", overall: 66 },
    { nome: "Gil", posicao: "ZAG", overall: 75 },
    { nome: "Jair", posicao: "ZAG", overall: 74 },
    { nome: "Luan Peres", posicao: "ZAG", overall: 74 },
    { nome: "Escobar", posicao: "LAT", overall: 74 },
    { nome: "Hayner", posicao: "LAT", overall: 73 },
    { nome: "Diego Pituca", posicao: "VOL", overall: 76 },
    { nome: "João Schmidt", posicao: "VOL", overall: 75 },
    { nome: "Giuliano", posicao: "MEI", overall: 76 },
    { nome: "Otero", posicao: "MEI", overall: 74 },
    { nome: "Patrick", posicao: "MEI", overall: 73 },
    { nome: "Guilherme", posicao: "ATA", overall: 76 },
    { nome: "Julio Furch", posicao: "ATA", overall: 75 },
    { nome: "Willian Bigode", posicao: "ATA", overall: 72 }
  ],
  vit: [
    { nome: "Lucas Arcanjo", posicao: "GOL", overall: 73 },
    { nome: "Muriel", posicao: "GOL", overall: 67 },
    { nome: "Wagner Leonardo", posicao: "ZAG", overall: 75 },
    { nome: "Neris", posicao: "ZAG", overall: 72 },
    { nome: "Edu", posicao: "ZAG", overall: 70 },
    { nome: "Lucas Esteves", posicao: "LAT", overall: 72 },
    { nome: "Raúl Cáceres", posicao: "LAT", overall: 70 },
    { nome: "Willian Oliveira", posicao: "VOL", overall: 72 },
    { nome: "Léo Naldi", posicao: "VOL", overall: 70 },
    { nome: "Matheusinho", posicao: "MEI", overall: 74 },
    { nome: "Jean Mota", posicao: "MEI", overall: 71 },
    { nome: "Filipe Machado", posicao: "MEI", overall: 71 },
    { nome: "Alerrandro", posicao: "ATA", overall: 74 },
    { nome: "Gustavo Mosquito", posicao: "ATA", overall: 73 },
    { nome: "Janderson", posicao: "ATA", overall: 71 }
  ],
  juv: [
    { nome: "Gabriel", posicao: "GOL", overall: 72 },
    { nome: "Mateus Claus", posicao: "GOL", overall: 66 },
    { nome: "Danilo Boza", posicao: "ZAG", overall: 73 },
    { nome: "Zé Marcos", posicao: "ZAG", overall: 71 },
    { nome: "Rodrigo Sam", posicao: "ZAG", overall: 70 },
    { nome: "Alan Ruschel", posicao: "LAT", overall: 72 },
    { nome: "João Lucas", posicao: "LAT", overall: 71 },
    { nome: "Jadson", posicao: "VOL", overall: 72 },
    { nome: "Mandaca", posicao: "VOL", overall: 70 },
    { nome: "Nenê", posicao: "MEI", overall: 72 },
    { nome: "Jean Carlos", posicao: "MEI", overall: 72 },
    { nome: "Luís Oyama", posicao: "MEI", overall: 70 },
    { nome: "Gilberto", posicao: "ATA", overall: 73 },
    { nome: "Erick Farias", posicao: "ATA", overall: 71 },
    { nome: "Marcelinho", posicao: "ATA", overall: 70 }
  ],
  mir: [
    { nome: "Alex Muralha", posicao: "GOL", overall: 71 },
    { nome: "Vanderlei", posicao: "GOL", overall: 66 },
    { nome: "Luiz Otávio", posicao: "ZAG", overall: 71 },
    { nome: "João Victor", posicao: "ZAG", overall: 70 },
    { nome: "Gazal", posicao: "ZAG", overall: 69 },
    { nome: "Zeca", posicao: "LAT", overall: 71 },
    { nome: "Lucas Ramon", posicao: "LAT", overall: 69 },
    { nome: "Neto Moura", posicao: "VOL", overall: 71 },
    { nome: "Danielzinho", posicao: "VOL", overall: 71 },
    { nome: "Gabriel", posicao: "MEI", overall: 72 },
    { nome: "Chico Kim", posicao: "MEI", overall: 71 },
    { nome: "Isaque", posicao: "MEI", overall: 69 },
    { nome: "Dellatorre", posicao: "ATA", overall: 72 },
    { nome: "Fernandinho", posicao: "ATA", overall: 70 },
    { nome: "Iury Castilho", posicao: "ATA", overall: 70 }
  ]
};
